### PR TITLE
[CHERI] Fix Bounded Mem/Var Args layout on stack

### LINKED ISSUE #8: Incorrect code generation for memory arguments and variadic arguments under corner case
Consider the following example:
```
typedef struct {
    int x;
    int y;
    int z;
} Triple;

int f(int a, int b, int c, int d, int e, int f, int g, int h, int i, ...);

int g() {
    return f(0, 0, 0, 0, 0, 0, 0, 0, 0, (Triple){ 1, 2, 3 });
}
```

The generated code for `g` places the variadic argument (`Triple`) at offset 8 of the memory argument buffer rather than offset 16, which is expected for all variadic arguments. Indeed, the generated code for `f` assumes that the variadic argument begins at a 16-byte aligned offset.

```
#include <stdarg.h>
int f(int a, int b, int c, int d, int e, int f, int g, int h, int i, ...) {
    va_list args;
    va_start(args, i);
    Triple values = va_arg(args, Triple);
    va_end(args);
    return values.y;
}
```

Compiler ran under parameters: `clang -S -target riscv64-unknown-freebsd -Xclang -target-feature -Xclang +cheri-bounded-vararg -Xclang -target-feature -Xclang +cheri-bounded-memarg-caller -Xclang -target-feature -Xclang +cheri-bounded-memarg-callee -march=rv64gczcheripurecap -mabi=l64pc128d -mno-relax --sysroot=./sysroot-riscv64-purecap -Og`.

### PR DESCRIPTION
**Pull request by veselypeta**
Should fix #8 & #9 & #16 

Includes change from #13

### CODE REVIEW

File: llvm/lib/Target/RISCV/RISCVISelLowering.cpp [hunk 1]
```diff
@@ -16503,15 +16477,19 @@ SDValue RISCVTargetLowering::LowerCall(CallLoweringInfo &CLI,
...
+    if (FirstVAAddr != SDValue()) {
       SDValue VarArgs = DAG.getCSetBounds(
-          FirstAddr, DL, VAArgEndOffset - VAArgStartOffset, Align(),
+          FirstVAAddr, DL, VAArgEndOffset - VAArgStartOffset, Align(),
           "CHERI-RISCV variadic call lowering",
           cheri::SetBoundsPointerSource::Stack, "varargs call bounds setting");
       // clear write and execute permissions on varargs. Clearning other
       // permissions shouldn't be necessary since the capability is derived from
       // CSP and that shouldn't have these in the first place.
-      uint64_t PermMask = -1UL & ~(CAP_AP_X | CAP_AP_W);
```
Comment (dpgao) [inline llvm/lib/Target/RISCV/RISCVISelLowering.cpp:16514]: This pattern appears in `lowerVASTARTCap` but remains unfixed.

File: llvm/lib/Target/RISCV/RISCVISelLowering.cpp [hunk 2]
```diff
@@ -16503,15 +16477,19 @@ SDValue RISCVTargetLowering::LowerCall(CallLoweringInfo &CLI,
...
+      uint64_t ExecPerm =
+          Subtarget.hasStdExtZCheriPureCap() ? (1 << 17) : (1 << 1);
+      uint64_t WritePerm =
+          Subtarget.hasStdExtZCheriPureCap() ? (1 << 1) : (1 << 3);
```
Comment (dpgao) [inline llvm/lib/Target/RISCV/RISCVISelLowering.cpp]: And the value of `WritePerm` is still incorrect. It should be `1 << 0` as per the spec.

**Comment by dpgao** [comment]
This doesn't fix the first example in #8. The variadic argument of type `Triple` should begin at offset 16 of the memory argument buffer. But right now it begins at offset 8.

**Comment by dpgao** [comment]
And this doesn't fix the second example in #8. The call to `f` in `g` sets the memory argument buffer to `NULL` under `-Xclang -target-feature -Xclang +cheri-bounded-vararg -Xclang -target-feature -Xclang +cheri-bounded-memarg-caller -Xclang -target-feature -Xclang +cheri-bounded-memarg-callee`.
```
__uint128_t f(void* a, __uint128_t b, __uint128_t c, __uint128_t d, ...);

__uint128_t g() {
    return f((void*)0x1, 0, 0, 123, (__uint128_t)456, (__uint128_t)789);
}
```

**Comment by veselypeta** [comment]
Thanks @dpgao. It's proved quite tricky to get this right for RISCV. The issue I've come across is that `Triple` type is converted to `[2 x i64]` is llvm. In RISCV these are treated as separate arguments, but I need to align to up a slot boundary. I've made it work now, by picky backing on `functionArgumentNeedsConsecutiveRegisters` for purecap varargs. I think the layout is correct, now but I'm writing some tests for it now to make sure. Let me know if you still have any issues. 
Thanks :pray:

**Comment by dpgao** [comment]
Thanks! I think once #14 is addressed, the compiler will be able to build CheriBSD with the memory argument ABI successfully.

**Comment by dpgao** [comment]
All LGTM now.

I've only been able to test this PR after rebasing it onto https://github.com/veselypeta/cherillvm/commit/a7d84f51090f85f0ad9fb557069aef993168b815, so do you intend to merge this right now or wait until https://github.com/veselypeta/cherillvm/commits/codasip-rebased/ is first incorporated to the main branch here?

**Comment by veselypeta** [comment]
> wait until https://github.com/veselypeta/cherillvm/commits/codasip-rebased/ is first incorporated to the main branch here?

Yes I'm working on integrating the last changes from both codasip and cambridge into this branch and make this the default branch for cheri alliance before merging this. Is this is a blocker for you, let me know, but it it seems that your rebase is working for your purpose. Hopefully, this will be the default branch by the end of the week. :crossed_fingers:

**Comment by dpgao** [comment]
> > wait until https://github.com/veselypeta/cherillvm/commits/codasip-rebased/ is first incorporated to the main branch here?
> 
> Yes I'm working on integrating the last changes from both codasip and cambridge into this branch and make this the default branch for cheri alliance before merging this. Is this is a blocker for you, let me know, but it it seems that your rebase is working for your purpose. Hopefully, this will be the default branch by the end of the week. 🤞

Thank you! This is not a blocker for me at the moment but obviously it would be better if it gets merged.

**Comment by qwattash** [comment]
@dpgao @veselypeta I was looking around and found this open PR which looks like could be merged? I don't have a dependency on it, but it seems everybody agrees and it was just preempted by other work?
